# Generated by Django 5.2.1 on 2025-06-03 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='timeComentarios',
            field=models.TimeField(default='1:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensajes',
            name='timeMensajes',
            field=models.TimeField(default='1:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='timePublicacion',
            field=models.TimeField(default='1:00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
