# Generated by Django 5.2.1 on 2025-06-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comentarios_timecomentarios_mensajes_timemensajes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='timeComentarios',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fechaComentarios',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='fechaPublicaion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='timePublicacion',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
