# Generated by Django 5.2.1 on 2025-06-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_comentarios_timecomentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ImagenPerfil',
            field=models.TextField(blank=True),
        ),
    ]
