# Generated by Django 5.2.1 on 2025-06-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_imagenperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fechaComentarios',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
