import React from "react";

const Usuarios = () => {
  return (
    <div>
      <h2>Usuarios</h2>
      <p>En esta sección, los usuarios pueden gestionar su información, preferencias y actividades dentro del sistema.</p>

      <ul>
        <li><strong>Perfil:</strong> Edita tu información personal y foto de usuario.</li>
        <li><strong>Preferencias:</strong> Ajusta la configuración para mejorar tu experiencia.</li>
        <li><strong>Seguridad:</strong> Modifica contraseñas y verifica autenticaciones.</li>
        <li><strong>Historial:</strong> Consulta registros de actividad y acciones realizadas.</li>
        <li><strong>Soporte:</strong> Accede a ayuda y preguntas frecuentes.</li>
      </ul>
    </div>
  );
};

export default Usuarios;